<?php

use Illuminate\Database\Seeder;

class FoodTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('foods')->delete();
         
        DB::table('foods')->insert(array(

        array('type_id'=>'1','name'=>'Fried Wonton','price'=>'130'),
        array('type_id'=>'1','name'=>'Fish chips','price'=>'120'),
        array('type_id'=>'1','name'=>'French Fry','price'=>'120'),
        array('type_id'=>'1','name'=>'Spice Potato','price'=>'120'),
        array('type_id'=>'1','name'=>'Special Wonton','price'=>'180'),
        array('type_id'=>'1','name'=>'Fried Chicken Wings','price'=>'200'),
        array('type_id'=>'1','name'=>'Vegetable Cutlet','price'=>'160'),
        array('type_id'=>'1','name'=>'Spring Rolls','price'=>'140'),

        array('type_id'=>'2','name'=>'Cutlet(beef/chicken)','price'=>'200'),
        array('type_id'=>'2','name'=>'Master Chef special fried boll plate(prawn/chicken)','price'=>'260'),
        array('type_id'=>'2','name'=>'Chicken drum sticks','price'=>'200'),
        array('type_id'=>'2','name'=>'Fish Cake(prawn/desi fish)','price'=>'250'),
        array('type_id'=>'2','name'=>'Master Chef special egg rolls(fish/chicken)','price'=>'280'),
        array('type_id'=>'2','name'=>'Master Chef special sesame(prawn/chicken)','price'=>'280'),
        array('type_id'=>'2','name'=>'Prawn/chicken on toast','price'=>'240'),
        array('type_id'=>'2','name'=>'Sze chuan wonton','price'=>'180'),
		
		array('type_id'=>'3','name'=>'Chicken-cashew nut salad','price'=>'370'),
		array('type_id'=>'3','name'=>'Chicken and prawn-cashew nut salad','price'=>'400'),
		array('type_id'=>'3','name'=>'Lab gai','price'=>'300'),
		array('type_id'=>'3','name'=>'Master Chef Special griled(beef/chicken) salad','price'=>'340'),
		array('type_id'=>'3','name'=>'prawn salad','price'=>'370'),
		array('type_id'=>'3','name'=>'Sze chuan chicken and prawn salad','price'=>'350'),
		
		array('type_id'=>'4','name'=>'Vegetable soup','price'=>'130'),
		array('type_id'=>'4','name'=>'Chicken clear soup','price'=>'130'),
		array('type_id'=>'4','name'=>'Chicken vegetable soup','price'=>'140'),
		array('type_id'=>'4','name'=>'Sweet corn soup','price'=>'150'),
		array('type_id'=>'4','name'=>'Chicken corn soup','price'=>'160'),
		array('type_id'=>'4','name'=>'Prawn corn soup','price'=>'200'),
		array('type_id'=>'4','name'=>'Special corn soup','price'=>'180'),
		array('type_id'=>'4','name'=>'Thai soup','price'=>'180'),
		array('type_id'=>'4','name'=>'Special Thai soup','price'=>'200'),
		array('type_id'=>'4','name'=>'Special mixed Thai vegetable soup','price'=>'200'),

		
		array('type_id'=>'5','name'=>'Jack soup','price'=>'250'),
		array('type_id'=>'5','name'=>'Special hot and sour soup','price'=>'250'),
		array('type_id'=>'5','name'=>'Special cocktail soup','price'=>'260'),
		array('type_id'=>'5','name'=>'Master Chef special soup','price'=>'300'),
		array('type_id'=>'5','name'=>'Thai hot and sour soup','price'=>'250'),
		array('type_id'=>'5','name'=>'Tam-yam goong soup','price'=>'300'),
		array('type_id'=>'5','name'=>'Sze chuan soup','price'=>'250'),
		array('type_id'=>'5','name'=>'Sze chuan Thai chili soup','price'=>'250'),

		
		array('type_id'=>'6','name'=>'Vegetable fried rice','price'=>'140'),
		array('type_id'=>'6','name'=>'Egg fried rice','price'=>'160'),
		array('type_id'=>'6','name'=>'Chicken fried rice','price'=>'180'),
		array('type_id'=>'6','name'=>'Beef fried rice','price'=>'190'),
		array('type_id'=>'6','name'=>'Prawn fried rice','price'=>'180'),
		array('type_id'=>'6','name'=>'Chicken/beef massala  rice','price'=>'200'),
		array('type_id'=>'6','name'=>'Prawn massala rice','price'=>'210'),
		array('type_id'=>'6','name'=>'Thai fried rice','price'=>'260'),
		array('type_id'=>'6','name'=>'Master Chef special fried rice','price'=>'270'),
		
		
		array('type_id'=>'7','name'=>'Master Chef fried chicken','price'=>'280'),
		array('type_id'=>'7','name'=>'Fried chicken with onion chili','price'=>'290'),
		array('type_id'=>'7','name'=>'Chicken chili onion','price'=>'300'),
		array('type_id'=>'7','name'=>'Chicken chili onion dry','price'=>'310'),
		array('type_id'=>'7','name'=>'Slice chicken chili','price'=>'300'),
		array('type_id'=>'7','name'=>'Chicken with garlic and chili','price'=>'300'),
		array('type_id'=>'7','name'=>'Sweet and sour chicken ball','price'=>'300'),
		
		
		array('type_id'=>'8','name'=>'Slice chicken with cashwe nut(spice)','price'=>'320'),
		array('type_id'=>'8','name'=>'Master Chef massala chicken','price'=>'300'),
		array('type_id'=>'8','name'=>'Master Chef lemon chicken','price'=>'300'),
		array('type_id'=>'8','name'=>'Master Chef special chicken jal fry(curry)','price'=>'300'),
		array('type_id'=>'8','name'=>'Master Chef chicken sizzling','price'=>'330'),


		array('type_id'=>'9','name'=>'Sweet and sour beef','price'=>'290'),
		array('type_id'=>'9','name'=>'Sweet and sour beef boll','price'=>'290'),
		array('type_id'=>'9','name'=>'Hot and sour beef','price'=>'290'),
		array('type_id'=>'9','name'=>'Slice of beef with vegetable','price'=>'170'),
		array('type_id'=>'9','name'=>'Slice of beef with mushroom and vegetable','price'=>'220'),
		array('type_id'=>'9','name'=>'Beef chili onion','price'=>'290'),
		array('type_id'=>'9','name'=>'Beef chili dry','price'=>'290'),
		array('type_id'=>'9','name'=>'Beef chili gravy','price'=>'290'),

		array('type_id'=>'10','name'=>'Master Chef special beef massala','price'=>'310'),
		array('type_id'=>'10','name'=>'Master Chef special beef sizzling','price'=>'350'),

		array('type_id'=>'11','name'=>'Mutton green chili onion','price'=>'330'),
		array('type_id'=>'11','name'=>'Mutton chili gravy','price'=>'330'),
		array('type_id'=>'11','name'=>'Mutton chili dry','price'=>'330'),
		array('type_id'=>'11','name'=>'Mutton sizzling','price'=>'400'),

		array('type_id'=>'12','name'=>'Sweet and sour prawn','price'=>'310'),
		array('type_id'=>'12','name'=>'Sweet and sour prawn ball','price'=>'320'),
		array('type_id'=>'12','name'=>'Hot sauce prawn','price'=>'310'),
		array('type_id'=>'12','name'=>'Prawn with garlic sauce','price'=>'310'),
		array('type_id'=>'12','name'=>'Prawn chili dry','price'=>'310'),
		array('type_id'=>'12','name'=>'Prawn with onion and chili','price'=>'310'),
		array('type_id'=>'12','name'=>'Prawn with mushroom ginger','price'=>'310'),
		array('type_id'=>'12','name'=>'prawn with vegetable','price'=>'260'),

		array('type_id'=>'13','name'=>'Master Chef special king prawn','price'=>'360'),
		array('type_id'=>'13','name'=>'Prawn with basil leaf gravy','price'=>'320'),
		array('type_id'=>'13','name'=>'China prawn','price'=>'380'),
		array('type_id'=>'13','name'=>'Prawn sizzlings','price'=>'400'),

		
		array('type_id'=>'14','name'=>'Slice fish with vegetable','price'=>'220'),
		array('type_id'=>'14','name'=>'Hot sauce fish','price'=>'350'),
		array('type_id'=>'14','name'=>'Sweet and sour fish','price'=>'350'),
		array('type_id'=>'14','name'=>'Fish chili dry','price'=>'350'),
		array('type_id'=>'14','name'=>'Fish with ginger and mushroom','price'=>'350'),

		
		array('type_id'=>'15','name'=>'Pomfret fried(Seasonal)','price'=>'360'),
		array('type_id'=>'15','name'=>'Stream pomfret(Seasonal)','price'=>'360'),
		array('type_id'=>'15','name'=>'Sweet and sour pomfret(Seasonal)','price'=>'370'),
		array('type_id'=>'15','name'=>'Pomfret with garlic sauce(Seasonal)','price'=>'360'),
		array('type_id'=>'15','name'=>'Sweet and sour red snapper(Seasonal)','price'=>'430'),
		array('type_id'=>'15','name'=>'Master Chef special red snapper(Seasonal)','price'=>'450'),

		array('type_id'=>'16','name'=>'Vegetable chowmein','price'=>'230'),
		array('type_id'=>'16','name'=>'Chowmein with(chicken/prawn/beef/mutton)','price'=>'260'),
		array('type_id'=>'16','name'=>'Master Chef special chowmein','price'=>'300'),

		array('type_id'=>'17','name'=>'Mixed vegetable chopsuey','price'=>'230'),
		array('type_id'=>'17','name'=>'Chopsuey with(chicken/prawn/beef/mutton)','price'=>'270'),
		array('type_id'=>'17','name'=>'American chopseuy','price'=>'280'),
		array('type_id'=>'17','name'=>'Chinese chopsuey','price'=>'260'),
		array('type_id'=>'17','name'=>'Master Chef special chopsuey','price'=>'300'),

		array('type_id'=>'18','name'=>'Plain vegetable','price'=>'150'),
		array('type_id'=>'18','name'=>'Steam vegetable','price'=>'150'),
		array('type_id'=>'18','name'=>'Mixed vegetable with(chicken/prawn/beef/mutton)','price'=>'150'),
		array('type_id'=>'18','name'=>'Mixed vegetable with oyster sauce','price'=>'150'),
		array('type_id'=>'18','name'=>'Master Chef special mixed vegetable','price'=>'230'),
				
		array('type_id'=>'19','name'=>'Thai fried rice','price'=>'250'),
		array('type_id'=>'19','name'=>'Thai vegetable with prawn,chicken,mushroom and chili','price'=>'250'),
		array('type_id'=>'19','name'=>'Thai mushroom vegetable','price'=>'320'),
		array('type_id'=>'19','name'=>'Thai mixed vegetable with oyster sauce','price'=>'300'),
		array('type_id'=>'19','name'=>'Thai fried chicken','price'=>'350'),
		array('type_id'=>'19','name'=>'Thai massala chicken','price'=>'300'),
		array('type_id'=>'19','name'=>'Thai boneless chicken','price'=>'310'),
		array('type_id'=>'19','name'=>'Thai boneless massala chicken','price'=>'310'),
		array('type_id'=>'19','name'=>'Thai red curry with(chicken/prawn/beef/mutton)','price'=>'300'),
		array('type_id'=>'19','name'=>'Thai beef chili dry','price'=>'300'),
		array('type_id'=>'19','name'=>'Thai mutton chili dry','price'=>'300'),
		array('type_id'=>'19','name'=>'Bangkok style vegetable','price'=>'280'),

		array('type_id'=>'20','name'=>'Bangkok style fried chicken','price'=>'300'),
		array('type_id'=>'20','name'=>'Thai sizzling with(chicken/prawn/beef/mutton) ','price'=>'370'),
		array('type_id'=>'20','name'=>'Bangkok style sizzling with(chicken/prawn/beef/mutton)','price'=>'380'),
		array('type_id'=>'20','name'=>'Shanghai style sizzling with(chicken/prawn/beef/mutton)','price'=>'380'),
		array('type_id'=>'20','name'=>'Prawn with garlic and soya sauce','price'=>'380'),
		array('type_id'=>'20','name'=>'Fried king prawn with garlic sauce','price'=>'440'),
		array('type_id'=>'20','name'=>'Duck(massala/paprika)','price'=>'450'),
				
		array('type_id'=>'21','name'=>'Sze-chuan fried rice','price'=>'240'),
		array('type_id'=>'21','name'=>'Sze-chuan vegetable with chicken','price'=>'200'),
		array('type_id'=>'21','name'=>'Sze-chuan fried Chicken','price'=>'300'),
		array('type_id'=>'21','name'=>'Sze-chuan fish chili dry','price'=>'250'),
		array('type_id'=>'21','name'=>'Sze-chuan prawn chili dry','price'=>'280'),
		array('type_id'=>'21','name'=>'Sze-chuan beef chili dry','price'=>'300'),
		array('type_id'=>'21','name'=>'Sze-chuan mutton chili dry','price'=>'310'),
		array('type_id'=>'21','name'=>'Sze-chuan beef with ginger and white pepper','price'=>'240'),
		array('type_id'=>'21','name'=>'Sze-chuan fish chili gravy','price'=>'280'),
		array('type_id'=>'21','name'=>'Sze-chuan prawn chili gravy','price'=>'275'),
		array('type_id'=>'21','name'=>'Sze-chuan beef chili gravy','price'=>'280'),
		array('type_id'=>'21','name'=>'Sze-chuan mutton chili gravy','price'=>'290'),
		array('type_id'=>'21','name'=>'Sze-chuan slice chicken gravy','price'=>'260'),
		array('type_id'=>'21','name'=>'Sze-chuan boneless chicken','price'=>'280'),
		array('type_id'=>'21','name'=>'Sze-chuan mushroom gravy with(chicken/beef)','price'=>'300'),
		array('type_id'=>'21','name'=>'Sze-chuan mutton with mushroom gravy','price'=>'310'),
		array('type_id'=>'21','name'=>'Sze-chuan prawn with mushroom gravy','price'=>'320'),
		
		array('type_id'=>'22','name'=>'Sze-chuan full chicken','price'=>'350'),
		array('type_id'=>'22','name'=>'Sze-chuan duck with lemon sauce','price'=>'433'),
		array('type_id'=>'22','name'=>'Sze-chuan lobster','price'=>'530'),
		
		array('type_id'=>'23','name'=>'Vegetable pakora','price'=>'140'),
		array('type_id'=>'23','name'=>'Chicken pakora','price'=>'180'),
		array('type_id'=>'23','name'=>'Prawn or poneer pakora','price'=>'160'),
		array('type_id'=>'23','name'=>'Raita salad','price'=>'140'),
		array('type_id'=>'23','name'=>'Mixed salad','price'=>'100'),
		
		array('type_id'=>'24','name'=>'Plain polau','price'=>'160'),
		array('type_id'=>'24','name'=>'Vegetable polau','price'=>'180'),
		array('type_id'=>'24','name'=>'Motor polau','price'=>'200'),
		array('type_id'=>'24','name'=>'Jira polau','price'=>'180'),
		array('type_id'=>'24','name'=>'Kashmiri polau','price'=>'220'),
		array('type_id'=>'24','name'=>'Haidarabadi biriany with chicken','price'=>'360'),
		array('type_id'=>'24','name'=>'Haidarabadi biriany with desi sauce','price'=>'360'),
		array('type_id'=>'24','name'=>'Haidarabadi biriany with prawn','price'=>'370'),
		array('type_id'=>'24','name'=>'Dum Biriany(chicken/mutton)','price'=>'370'),
		array('type_id'=>'24','name'=>'Special biriany','price'=>'400'),
		
		array('type_id'=>'25','name'=>'Plain Nun','price'=>'40'),
		array('type_id'=>'25','name'=>'Butter Nan','price'=>'45'),
		array('type_id'=>'25','name'=>'Garlic Nan','price'=>'45'),
		array('type_id'=>'25','name'=>'Kashmiri Nan','price'=>'60'),
		array('type_id'=>'25','name'=>'Special Nan','price'=>'70'),
		
		array('type_id'=>'26','name'=>'Achari Aloo','price'=>'200'),
		array('type_id'=>'26','name'=>'Shobji(joypuri/milijhili/kalapuri)','price'=>'180'),
		array('type_id'=>'26','name'=>'Palok ponner','price'=>'200'),
		array('type_id'=>'26','name'=>'Motar ponner','price'=>'199'),
		array('type_id'=>'26','name'=>'Ponner makhani','price'=>'220'),
		array('type_id'=>'26','name'=>'Tondoori vegetable','price'=>'200'),
		array('type_id'=>'26','name'=>'Vegetable jhal fry','price'=>'180'),
		array('type_id'=>'26','name'=>'Dal butter fry','price'=>'150'),
		array('type_id'=>'26','name'=>'Tarka dal','price'=>'140'),
		array('type_id'=>'26','name'=>'Dal makhani','price'=>'180'),

		array('type_id'=>'27','name'=>'Achari chicken','price'=>'320'),
		array('type_id'=>'27','name'=>'Butter chicken','price'=>'300'),
		array('type_id'=>'27','name'=>'Chicken tikka massala','price'=>'300'),
		array('type_id'=>'27','name'=>'Chicken jhal fry','price'=>'300'),
		array('type_id'=>'27','name'=>'Chicken dopiaza','price'=>'300'),
		array('type_id'=>'27','name'=>'Chicken bhuna','price'=>'300'),
		array('type_id'=>'27','name'=>'Chicken roast','price'=>'300'),
		array('type_id'=>'27','name'=>'Chicken korma','price'=>'300'),
		array('type_id'=>'27','name'=>'Karai chicken','price'=>'320'),
		array('type_id'=>'27','name'=>'Resmi tikka massala','price'=>'300'),
	
		array('type_id'=>'28','name'=>'Beef achari','price'=>'310'),
		array('type_id'=>'28','name'=>'Beef bhuna','price'=>'300'),
		array('type_id'=>'28','name'=>'Beef karai','price'=>'300'),
		array('type_id'=>'28','name'=>'Beef massala','price'=>'300'),
		array('type_id'=>'28','name'=>'Beef jhal fry','price'=>'300'),

		array('type_id'=>'29','name'=>'Mutton(achari/bhuna/massala)','price'=>'320'),
		array('type_id'=>'29','name'=>'Mutton hundi','price'=>'310'),
		array('type_id'=>'29','name'=>'Mutton karai','price'=>'310'),
		array('type_id'=>'29','name'=>'Mutton korma','price'=>'310'),
		array('type_id'=>'29','name'=>'Mutton roganjosh','price'=>'310'),

		array('type_id'=>'30','name'=>'Prawn dopiaza','price'=>'300'),
		array('type_id'=>'30','name'=>'Prawn malai curry','price'=>'300'),
		array('type_id'=>'30','name'=>'Prawn butter massala','price'=>'300'),
		array('type_id'=>'30','name'=>'Prawn karai','price'=>'300'),
		array('type_id'=>'30','name'=>'Tiger prawn(bhana/massala)','price'=>'300'),

		array('type_id'=>'31','name'=>'Fish (butter/tikka) massala','price'=>'300'),
		array('type_id'=>'31','name'=>'Fish karai','price'=>'300'),
		array('type_id'=>'31','name'=>'Pomfret(bhana/fry/massala)','price'=>'370'),
		array('type_id'=>'31','name'=>'Red snapper(bhana/fry/massala)','price'=>'480'),
		array('type_id'=>'31','name'=>'Vetki(boneless) massala or dopiaza','price'=>'330'),

		array('type_id'=>'32','name'=>'Fish tikka kebab','price'=>'300'),
		array('type_id'=>'32','name'=>'Resmi kebab','price'=>'280'),
		array('type_id'=>'32','name'=>'Tengri kebab','price'=>'370'),
		array('type_id'=>'32','name'=>'Beef botti kebab','price'=>'300'),
		array('type_id'=>'32','name'=>'Mutton botti kebab','price'=>'300'),
		array('type_id'=>'32','name'=>'Chicken tondoori(1/2)','price'=>'200'),
		array('type_id'=>'32','name'=>'Full chicken tondoori','price'=>'400'),
		array('type_id'=>'32','name'=>'Prawn tondoori','price'=>'400'),
		array('type_id'=>'32','name'=>'Pomfret tondoori','price'=>'380'),
		array('type_id'=>'32','name'=>'Beef stack tondoori','price'=>'340'),
		
		array('type_id'=>'33','name'=>'Plain rice(as much as you can)','price'=>'30'),
		array('type_id'=>'33','name'=>'Stream rice(minimum for 3 pax)','price'=>'40'),
		array('type_id'=>'33','name'=>'Seasonal vegetable(Bangladesh style)','price'=>'25'),
		array('type_id'=>'33','name'=>'Dal','price'=>'30'),
		array('type_id'=>'33','name'=>'Thick dal','price'=>'35'),
		array('type_id'=>'33','name'=>'Murigonto','price'=>'35'),
		array('type_id'=>'33','name'=>'Aloo vorta','price'=>'15'),
		array('type_id'=>'33','name'=>'Shtki vorta','price'=>'40'),
		array('type_id'=>'33','name'=>'Prawn vorta','price'=>'45'),
		array('type_id'=>'33','name'=>'Taki vorta','price'=>'40'),
		array('type_id'=>'33','name'=>'Potol/tomato vorta(seasonal)','price'=>'35'),
		array('type_id'=>'33','name'=>'Beef bhuna','price'=>'100'),
		array('type_id'=>'33','name'=>'Mutton bhuna','price'=>'120'),
		array('type_id'=>'33','name'=>'Chicken bhuna','price'=>'100'),
		array('type_id'=>'33','name'=>'Fish(rui/katol)','price'=>'100'),
		array('type_id'=>'33','name'=>'Sutki curry','price'=>'100'),
		array('type_id'=>'33','name'=>'Koi fish','price'=>'140'),
		array('type_id'=>'33','name'=>'Hilsha fish','price'=>'150'),
		array('type_id'=>'33','name'=>'Small fish','price'=>'70'),
		array('type_id'=>'33','name'=>'Salad','price'=>'20'),
		
		array('type_id'=>'34','name'=>'Chicken roll','price'=>'35'),
		array('type_id'=>'34','name'=>'Vegetable roll','price'=>'30'),
		array('type_id'=>'34','name'=>'Fried chicken burger','price'=>'75'),
		array('type_id'=>'34','name'=>'Chicken burger','price'=>'50'),
		array('type_id'=>'34','name'=>'Chicken & cheese burger','price'=>'55'),
		array('type_id'=>'34','name'=>'Chicken bon','price'=>'40'),
		array('type_id'=>'34','name'=>'Hot dog','price'=>'40'),
		array('type_id'=>'34','name'=>'Toasted chicken sandwich','price'=>'35'),
		array('type_id'=>'34','name'=>'Toasted chicken & cheese sandwich','price'=>'45'),
		array('type_id'=>'34','name'=>'Club sandwich','price'=>'50'),
		
		array('type_id'=>'35','name'=>'Ice-cream(2 scoop)','price'=>'50'),
		array('type_id'=>'35','name'=>'Fessh food salad with ice-cream','price'=>'80'),
		array('type_id'=>'35','name'=>'Banana split','price'=>'50'),
		array('type_id'=>'35','name'=>'Fresh fruit platter','price'=>'50'),
		array('type_id'=>'35','name'=>'Egg pudding','price'=>'50'),

		array('type_id'=>'36','name'=>'Mineral water(500ml)','price'=>'20'),
		array('type_id'=>'36','name'=>'Mineral water(1.5liter)','price'=>'30'),
		array('type_id'=>'36','name'=>'Soft drink(per glass)','price'=>'20'),
		array('type_id'=>'36','name'=>'Soft drink(can)','price'=>'45'),
		array('type_id'=>'36','name'=>'Energy drink(Speed)','price'=>'40'),
		array('type_id'=>'36','name'=>'Fruit juice','price'=>'30'),
		array('type_id'=>'36','name'=>'Fruit punch','price'=>'50'),
		array('type_id'=>'36','name'=>'Fresh fruit juice(orange/apple/mango/papaya)','price'=>'60'),
		array('type_id'=>'36','name'=>'Milk shake(vanilla/chocolate/stoaberry)','price'=>'50'),
		array('type_id'=>'36','name'=>'Siberian brazes','price'=>'60'),
		array('type_id'=>'36','name'=>'Special lassi','price'=>'50'),
		array('type_id'=>'36','name'=>'Tea(milk tea/ice tea/leamon tea)','price'=>'20'),
		array('type_id'=>'36','name'=>'Coffee(milk coffee/cold coffee)','price'=>'50'),
		array('type_id'=>'36','name'=>'Black coffee','price'=>'50'),
		array('type_id'=>'36','name'=>'Black frappe','price'=>'50'),

        //array(pe'=>'','name'=>'','price'=>''),	
          ));
    }
}
